import { Inter, Roboto } from "next/font/google";
import "./globals.css";
// import Header from "./Header";
import dynamic from "next/dynamic";
const Header = dynamic(() => import("./Header"));


// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Salon Website",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: ['400', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
