"use client";
import { Inter, Roboto } from "next/font/google";
import "./globals.css";
// import Header from "./Header";
import dynamic from "next/dynamic";
const useRouter = dynamic(() => import("next/router").then((router) => router.useRouter()));
const Header = dynamic(() => import("./Header"));
const Footer = dynamic(() => import("./Footer"));

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Salon Website",
//   description: "Generated by create next app",
// };

const roboto = Roboto({
  weight: ["400", "700", "900", "300", "100"],
  style: ["normal", "italic"],
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({ children }) {
  const router = useRouter();
  const { asPath } = router;

  const excludedPath = ["/sign-in"];

  // const hideHeaderFooter = excludedPath.includes(router.pathname);

  return (
    <html lang="en">
      <body className={roboto.className}>
        {excludedPath.includes(asPath) ? null : <Header />}
        {children}
        {excludedPath.includes(asPath) ? null : (
          <div className="pt-24">
            <Footer />
          </div>
        )}
      </body>
    </html>
  );
}
